export const  serviceData=[
    {       
        id:1,
        servicename:"Gst Registration" ,
        price: "599/-" ,
        mprice:"1599/-",
        gst:"707/-",
        save:"1292/- (10%)",
        description:"Get GST certificate @ Rs 250 with dedicated professional team support GST registration will be done within 3 days. Send all supporting documents and get proficient help and guidance" ,
        icon: "fa fa-globe ",
        color: "blue",
        sddescription1:"Apply for GST Registration Online in India with Vanigasevai! As per GST legal process, any business operation or any entity with an annual turnover exceeding Rs 40 lakhs must undergo the GST process/procedure in India as a separate taxable provisio.",
        sddescription2:" As per GST jurisdiction, any business operations whose annual turnover exceeds Rs 40 lakhs must register as a separate taxable provision. This procedure is called GST registration. It takes around 2-6 working days to obtain GST registration online in India." ,
        q1:"Overview of GST Registration Online in India ",
        p1:"Goods and Services Tax, or GST, is a tax levied on all products and services purchased in India. Taxation, value-added tax, and services tax are some indirect taxes replaced in India by the goods and services tax (GST), which is also an indirect tax. According to the Goods and Service Tax Act, which the Indian Government approved on March 29, 2017, the Goods and Service Tax (GST) has been in effect since July 1, 2017. As per GST jurisdiction, if you do business without GST registration, it is considered an offence.",
        q2:"GST Registration Online in India or Goods and Service Tax - One Nation One Tax",
        p2:"Being the biggest tax reform in India, GST is levied on goods and services. This includes both Central taxes (CST, Service Tax, Excise Duty) and State taxes (VAT, Entertainment Tax, Luxury Tax, Octroi). This will help the consumer to bear only GST charged by the last dealer in the chain of trade and supply.     As per GST Regime, any company whose annual turnover is more than Rs.40 lakh is required to register as a normal taxable individual. However, there is an exclusion for hill states and the North East, where the annual turnover exceeds Rs.20 lakh for them. As per GST Regime, any company whose annual turnover is more than Rs.40 lakh is required to register as a normal taxable individual. However, there is an exclusion for hill states and the North East, where the annual turnover exceeds Rs.20 lakh for them. Obtaining GST Registration in India is mandatory for all types of businesses whose turnover meets the above-mentioned criteria. If a business entity carries out any business activities without GST registration, it will be conceived as a punishable offense and the business and its owner will be liable to pay heavy penalties and legal issues." ,
    },
    {       
        id:2,
        servicename:"Import & Export code" ,
        price: "1200/-" ,
        mprice:"2000/-",
        gst:"1500/-",
        save:"500/- (10%)",
        description:"Apply for IEC registration online Now! And get the 10-digit IEC code. Without IEC, primarily importers merchants cannot import products, and primarily exporters merchants cannot receive benefits from DGFT." ,
        icon: "fa fa-exchange",
        color: "blue",
        sddescription1:"Get your IE Code Registration done online with us today! It is mandatory for all Indian companies that deal or plan to expand their business activities through import and export business operations. In India, the Director-General of Foreign Trade (DGFT), under the Department of Commerce, issues an online computer registration for companies and businesses dealing in imports/exports in the Indian territory1",
        sddescription2:"" ,
        q1:"Overview of IEC Registration Online in India" ,
        p1:"IEC Registration is required for anyone looking to start an import/export business registration in India. Documents required for IEC Registration (Import Export Code). Register import export code (IEC) in India Register for IE Code online in India with us! It is mandatory for all Indian companies that deal with or plan to expand their business activities through import and export business operations. Online IE Code Registration is a mandatory 10-digit identifying license, for companies and businesses that deal with import-export transactions in the Indian Territory issued by The Director-General of Foreign Trade (DGFT), under the Department of Commerce, in India. " ,
        q2:"" ,
        p2:"" ,

        
    },
    {       
        id:3,
        servicename:"Trademark" ,
        price: "1200/-" ,
        mprice:"2000/-",
        gst:"1500/-",
        save:"500/- (10%)",
        description:"Get trademark for your brand name or logo with unique identity and secure legal protection within a week! Get trademark registration for any sign you use to identify your business." ,
        icon: "fa fa-user-circle ",
        color: "blue",
        sddescription1:"Trademark registration in India is essential for businesses looking to establish an individual identity on the market. A registered trademark can be a symbol, image, phrase, word, sound, graphic, or color scheme that distinguishes your products or services from competitors. Vanigasevai specialists offer trademark registration services online, making it convenient for businesses to secure their brand's future success. By registering your brand name, you can gain a competitive advantage in the market and protect your distinctive identity. Don't forget to prioritize trademark registration in India and brand name registration in India to safeguard your business.",
        sddescription2:"" ,
        q1:"" ,
        p1:"" ,
        q2:"" ,
        p2:"" ,

    },
    {       
        id:4,
        servicename:"One Person Company" ,
        price: "1200/-" ,
        mprice:"2000/-",
        gst:"1500/-",
        save:"500/- (10%)",
        description:"OPC is a business owned by one owner. Before the Companies Act 2013, a company could only be founded with two directors and members." ,
        icon: "fa fa-certificate",
        color: "blue",
        sddescription1:"OPC, or One Person Company, is a business setup owned by a single individual. It was a concept not available until the Companies Act 2013, which allowed businesses to be formed with one director and member. OPCs provide the same benefits as any other company, but with the advantage that all decisions and operations can be carried out by a single individual. This makes OPCs an excellent solution for entrepreneurs who want to start their own businesses without extra help. With the Companies Act 2013, it is now easier than ever to register an OPC and start trading.",
        sddescription2:"" ,
        q1:"" ,
        p1:"" ,
        q2:"" ,
        p2:"" ,
        
        
    },
    {       
        id:5,
        servicename:"MSME Registration" ,
        price: "1200/-" ,
        mprice:"2000/-",
        gst:"1500/-",
        save:"500/- (10%)",
        description:"Registrations for manufacturing or service lines can be obtained through the MSME Act. This registration provides many benefits regarding taxation, business setup, credit facilities, loans, etc." ,
        icon: "fa fa-cubes",
        color: "blue",
        sddescription1:"Registering your small business under Udyog Aadhaar MSME online registration can grant you access to a variety of benefits, including tax exemptions, sector lending, capital investment, and power tariff grants. This is an incredibly valuable opportunity for small businesses, as MSMEs – or Micro, Small, and Medium Enterprises – are a crucial part of India's socio-economic development. It is essential for MSMEs to take advantage of Udyog Aadhaar MSME online registration in order to maximize their potential and to ensure the country's continued progress. This online registration process is fast and efficient, making it easy to access the many benefits that come with it. With the resources provided by Udyog Aadhaar MSME online registration, small businesses in India can thrive and contribute to the nation's continued growth and development.",
        sddescription2:"" 
    },
    {       
        id:6,
        servicename:"FSSAI / Food License" ,
        price: "1200/-" ,
        mprice:"2000/-",
        gst:"1500/-",
        save:"500/- (10%)",
        description:"Get FSSAI license Now! All manufacturers, traders, and restaurants operating any food business that includes manufacturing or processing are given a food license or FSSAI license." ,
        icon: "fa fa-facebook",
        color: "blue",
        sddescription1:"Apply for FSSAI License with Food Registration Online Consultant India ! Get real deals and juicy terms. Pay the charge at a reasonable rate. You can obtain your FSSAI license even before you get your food order! The main aim of the Food Safety and Standards Authority of India or FSSAI License Online is to reduce the chances of food adulteration, and substandard or inferior food products, and improve the accountability of makers by granting them a license for food service business.",
        sddescription2:"" ,
        q1:"" ,
        p1:"" ,
        q2:"" ,
        p2:"" ,
        
    },
    {       
        id:7,
        servicename:"LLP Registration" ,
        price: "1200/-" ,
        mprice:"2000/-",
        gst:"1500/-",
        save:"500/- (10%)",
        description:"Get started with LLP registration for your partnership business through Vanigasevai! Limit your liability and face more compliance issues than PLC registration." ,
        icon: "fa fa-file-text-o ",
        color: "blue",
        sddescription1:"LLP registration is a great way to get started with setting up a partnership business. By registering an LLP, you can benefit from limited liability protection, as the liability of all partners is limited to the amount of their capital contributions. As a result, LLP registration is more advantageous than PLC registration, which may expose partners to more liabilities.",
        sddescription2:"Vanigasevai offers the complete solution for LLP registration. We can help you register your business quickly and easily, and ensure that everything is done in compliance with the relevant regulations and laws. Our team is experienced in helping businesses of all sizes to register their LLP, making the process as simple and straightforward as possible." ,
        
    }
    ,
    {       
        id:8,
        servicename:" Pvt Ltd Company" ,
        price: "1200/-" ,
        mprice:"2000/-",
        gst:"1500/-",
        save:"500/- (10%)",
        description:"Register your Company with Vanigasevai in 7 days at the lowest price + DIN & DSC for 2 Directors + MOA & AOA + ROC Fees, PAN & TAN" ,
        icon: "fa fa-viacoin",
        color: "blue",
        sddescription1:"Vanigasevai is the one-stop destination for all your company registration needs. Our experts will help you get your venture registered in just 7 days at the lowest price. We help you register your company with the Ministry of Corporate Affairs (MCA) and provide you with a Director Identification Number (DIN) and Digital Signature Certificate (DSC) for two directors. We also provide Memorandum of Association (MOA) and Articles of Association (AOA) and register your company with the Registrar of Companies (ROC). Our services include PAN & TAN registration and ROC fees. So, what are you waiting for? Get in touch with us today and register your company with Vanigasevai.",
        sddescription2:"" ,
        
    }
    
    

    
]